name: Build & Push Docker to GHCR

# 触发条件：main 分支 push 或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 Buildx（支持多架构）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ 登录 GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ 构建并推送 Docker 镜像
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/barbaraklayne/xianyu-auto-reply:latest
          push: true
